#!/bin/sh
#Usage: 1 parameters: checkHostQuery :: String -> IO (Maybe Int)
ghc Queries.hs -e "checkHostQuery  $1 >>= (writeFile \"checkHost.output\") . show" 1>&2
cat checkHost.output
echo
rm checkHost.output
