#!/bin/sh
#Usage: 1 parameters: deleteDiskQuery :: Int -> IO Integer
ghc Queries.hs -e "deleteDiskQuery  $1 >>= (writeFile \"deleteDisk.output\") . show" 1>&2
cat deleteDisk.output
echo
rm deleteDisk.output
