#!/bin/sh
#Usage: 1 parameters: deletePartitionQuery :: Int -> IO Integer
ghc Queries.hs -e "deletePartitionQuery  $1 >>= (writeFile \"deletePartition.output\") . show" 1>&2
cat deletePartition.output
echo
rm deletePartition.output
