#!/bin/sh
#Usage: 1 parameters: stageHostQuery :: Int -> IO Integer
ghc Queries.hs -e "stageHostQuery  $1 >>= (writeFile \"stageHost.output\") . show" 1>&2
cat stageHost.output
echo
rm stageHost.output
